### ISSUE TITLE
CSS as a separate file

### ISSUE THREAD

**Issue by rorysedgwick** [jrans/nodediggity#16]
Best practice is to have your CSS in a separate file from your html and then import it into the html via a stylesheet link

**Comment by jackpandas** [comment]
Done!

**Comment by rorysedgwick** [comment]
Cool.  Usually it's best to let the person who opened the issue close it again once they're happy. But i'll let this one go

**Comment by jackpandas** [comment]
Sorry about that, didn't know... :/
